# Generated by Django 4.2.7 on 2023-11-13 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.ForeignKey(blank=True, help_text='Выберите расцветку одежды', null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.color'),
        ),
    ]
