# Generated by Django 4.2.7 on 2023-11-13 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Выберите название пола', max_length=255)),
            ],
            options={
                'verbose_name': 'Пол одежды',
                'verbose_name_plural': 'Пола одежды',
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.ForeignKey(blank=True, help_text='Введите пол', null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.gender'),
        ),
    ]
