# Generated by Django 4.2.7 on 2023-11-13 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_gender_alter_product_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='singular_name',
            field=models.CharField(default='Category', help_text='Введите название категории в единственном числе', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Введите название категории во множественном числе', max_length=255),
        ),
    ]
