# Generated by Django 4.2.7 on 2023-11-13 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_category_singular_name_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='manufacturer',
            field=models.ForeignKey(blank=True, help_text='Введите производителя', null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.manufacturer'),
        ),
    ]
