# Generated by Django 4.2.7 on 2023-11-18 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_gender_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gender',
            name='slug',
            field=models.SlugField(help_text='Сокращение для ссылки', max_length=200, unique=True),
        ),
    ]
