# Generated by Django 4.2.7 on 2023-11-18 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_manufacturer_image_alter_manufacturer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='slug',
            field=models.SlugField(default='now', help_text='Сокращение для ссылки', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(help_text='Сокращение для ссылки', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='gender',
            name='slug',
            field=models.SlugField(help_text='Сокращение для ссылки', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(help_text='Сокращение для ссылки', max_length=255),
        ),
    ]
