# Generated by Django 4.2.7 on 2023-11-18 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_manufacturer_slug_alter_category_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer',
            name='slug',
            field=models.SlugField(help_text='Сокращение для ссылки', max_length=255, unique=True),
        ),
    ]
